// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc9edES1If6cADNZdbwcOtXsV_AD71Qhk',
    appId: '1:976346295511:web:2def66c212c474508e5492',
    messagingSenderId: '976346295511',
    projectId: 'flutter-dash-g23',
    authDomain: 'flutter-dash-g23.firebaseapp.com',
    storageBucket: 'flutter-dash-g23.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuFIc7SpYjowJfnKe7EGPzT8BYBHYXLC0',
    appId: '1:976346295511:android:aa86b7593aa9c9b78e5492',
    messagingSenderId: '976346295511',
    projectId: 'flutter-dash-g23',
    storageBucket: 'flutter-dash-g23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-0HewtPFslRUj1viWNv1LiLGsbAZvySM',
    appId: '1:976346295511:ios:3cdfc4698767365a8e5492',
    messagingSenderId: '976346295511',
    projectId: 'flutter-dash-g23',
    storageBucket: 'flutter-dash-g23.appspot.com',
    iosClientId: '976346295511-ose8nb8bt7n92mvb4m9sv6f7gknkb8te.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleHackathon2023',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-0HewtPFslRUj1viWNv1LiLGsbAZvySM',
    appId: '1:976346295511:ios:dcbb4d03a14cd22b8e5492',
    messagingSenderId: '976346295511',
    projectId: 'flutter-dash-g23',
    storageBucket: 'flutter-dash-g23.appspot.com',
    iosClientId: '976346295511-spnjvp5q43mnlphmr1l2jiu1odfphv7r.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleHackathon2023.RunnerTests',
  );
}
