// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnPi9gkvlZAt5z5LRMh9T3Y3ulWDWKLTI',
    appId: '1:31112100824:web:e4d208c5bcf9197a0bd0ad',
    messagingSenderId: '31112100824',
    projectId: 'flutter-dash-g2023',
    authDomain: 'flutter-dash-g2023.firebaseapp.com',
    storageBucket: 'flutter-dash-g2023.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGp74TEXqyUy2zkek-i34W56wpZ1PfPJ4',
    appId: '1:31112100824:android:18df529e9fde83500bd0ad',
    messagingSenderId: '31112100824',
    projectId: 'flutter-dash-g2023',
    storageBucket: 'flutter-dash-g2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1kSY3wY3c5KH3IgiAY3FZIAQxXNVzy0w',
    appId: '1:31112100824:ios:b3a197bfa31146940bd0ad',
    messagingSenderId: '31112100824',
    projectId: 'flutter-dash-g2023',
    storageBucket: 'flutter-dash-g2023.appspot.com',
    iosClientId: '31112100824-nrhas4pe2lnnr8jlj4kpcn0ju17j5d7g.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleHackathon2023',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1kSY3wY3c5KH3IgiAY3FZIAQxXNVzy0w',
    appId: '1:31112100824:ios:a106bfea594a29220bd0ad',
    messagingSenderId: '31112100824',
    projectId: 'flutter-dash-g2023',
    storageBucket: 'flutter-dash-g2023.appspot.com',
    iosClientId: '31112100824-0m3m8v8gtd3mv60c4ma811rtun5cuatd.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleHackathon2023.RunnerTests',
  );
}
